on: [push, pull_request]
name: Test macOS
jobs:
  test:
    strategy:
      matrix:
        go-version: ["1.14", "1.x"]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Environment
        run: |
          echo GIT_VERSION=$(git describe --tags) >> $GITHUB_ENV
      - name: Test
        run: GO111MODULE=on go test -v ./...
