on: [push, pull_request]
name: Test Windows
jobs:
  test:
    strategy:
      matrix:
        go-version: ["1.14", "1.x"]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Environment
        run: |
          echo GIT_VERSION=$(git describe --tags) >> $GITHUB_ENV
      - name: Test
        env:
          CGO_ENABLED: 1
          GO111MODULE: "on"
        run: go test -v ./...
